# Generated by Django 4.2.5 on 2023-09-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_messages', to='chat.groupmember'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_messages', to='chat.groupmember'),
        ),
    ]
