# Generated by Django 4.2.5 on 2023-09-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_to_member_alter_message_from_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_messages', to='chat.groupmember'),
        ),
    ]
